### ISSUE TITLE
promiseの意味がないような

### ISSUE THREAD

**Issue by K-Wakui** [t-kinouchi/TrafficLight#10]
いまのだと結局スタート地点から
A→２秒後
B→４秒後
C→６秒後
を同時にやってます
そうじゃなくて
Aからスタートして
A→２秒後
それが終わったら
B→２秒後
それが終わったら
C→２秒後
という風に書いてほしいです。
違いが判らなかったら他の信号機を見るといいと思います。

**Comment by t-kinouchi** [comment]
今度こそできたのではないかと思います…
最初のクリックで全ボタンのdisableと青点灯、その後2秒毎に変化するpromiseを作りました。
