### ISSUE TITLE
"xxxxx"  'xxxxxx' の違い

### ISSUE THREAD

**Issue by K-Wakui** [t-kinouchi/TrafficLight#5]
classとid を書いている部分で２種類使っているのはなにか意味がありますか。

**Comment by t-kinouchi** [comment]
JavaScriptはシングルクォーテーション、と考えながら書いていたらHTMLの方で混ざってしまいました…。index.html内ではすべてダブルクォーテーション、main.js内ではすべてシングルクォーテーション、と統一させました。
