### ISSUE TITLE
promiseを使う

### ISSUE THREAD

**Issue by K-Wakui** [t-kinouchi/TrafficLight#6]
setTimeoutはpromiseと使う様にした方が良いです。調べてみて下さい。

**Comment by t-kinouchi** [comment]
遅くなりました。Promise.resolveでthenのチェーンにしてみました。この使い方で合っているでしょうか。。

**Comment by K-Wakui** [comment]
とりあえずあと少しって感じです。今のままだとissueに書いた通りになるので、とりあえず理解できなかったら、ほかのインターン生のみて見るのも1つの手だと思います。
